
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Nov 27 22:36:06 CET 2013
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 21;
  public static final int CHAR = 42;
  public static final int CONST = 5;
  public static final int GE = 35;
  public static final int LPAREN = 19;
  public static final int SEMI = 8;
  public static final int MINUS = 26;
  public static final int RPAREN = 20;
  public static final int AND = 39;
  public static final int LT = 36;
  public static final int OR = 38;
  public static final int BOOL = 43;
  public static final int COMMA = 7;
  public static final int CLASS = 9;
  public static final int DIV = 28;
  public static final int PLUS = 25;
  public static final int IF = 12;
  public static final int LSQBRACE = 17;
  public static final int DOT = 31;
  public static final int LE = 37;
  public static final int EOF = 0;
  public static final int MINUSMINUS = 22;
  public static final int RETURN = 16;
  public static final int EQUAL = 6;
  public static final int NEW = 30;
  public static final int error = 1;
  public static final int MUL = 27;
  public static final int NUMBER = 41;
  public static final int MOD = 29;
  public static final int NEQ = 33;
  public static final int IDENT = 45;
  public static final int BREAK = 15;
  public static final int VOID = 11;
  public static final int EQ = 32;
  public static final int ELSE = 40;
  public static final int LBRACE = 3;
  public static final int READ = 23;
  public static final int WHILE = 13;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 10;
  public static final int PROG = 2;
  public static final int STRING = 44;
  public static final int RSQBRACE = 18;
  public static final int GT = 34;
  public static final int PRINT = 24;
  public static final int DO = 14;
}

